name: flutter_native_timezone
description: A flutter plugin for displaying native Google Maps.
version: 1.0.1
author: Pinkfish <pinkfishfrog@gmail.com>
homepage: https://github.com/pinkfish/flutter_native_timezone

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
    sdk: '>=2.0.0 <3.0.0'

# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.whelksoft.timezone
    pluginClass: TimezonePlugin
