name: flutter_native_timezone
description: A flutter plugin for getting the local timezone of the os.
version: 1.0.4
author: Pinkfish <pinkfishfrog@gmail.com>
homepage: https://github.com/pinkfish/flutter_native_timezone

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  plugin:
    androidPackage: com.whelksoft.flutter_native_timezone
    pluginClass: FlutterNativeTimezonePlugin
